### ISSUE TITLE
Make --dry default and remove the flag

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/release-tool#14]
https://github.com/containerd/release-tool/blob/1808a54cbad02b6c565f0175e98a43e7497a9318/main.go#L272-L284

Non-dry mode is actually no-op, can we make `--dry` default and remove the flag?

@dmcgowan

**Comment by dmcgowan** [comment]
The idea was to generate the tag when the flag isn't provided. I didn't trust the tool for awhile to let it do that, but I think based on my own release flow today, it might just be worth it generating the tag. Originally the content was captured, verified, then used to create the tag and the Github release. Now we have a Github release which can generate release directly from the pushed tag and the caching makes verification via `--dry` easier.
